AWSTemplateFormatVersion: "2010-09-09"

Description: Template to deploy a Lambda function. NOTE - this creates a public Lambda function with a public HTTP endpoint. Please delete after you're done using.

Resources:

  # Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda-function
      Description: LambdaFunction using python3.12.
      Runtime: python3.12
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print(json.dumps(event))
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Handler: index.lambda_handler
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt LambdaRole.Arn

  # Reference: https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html
  # This creates a public HTTP endpoint for the Lambda function
  LambdaFunctionUrl:
   Type: AWS::Lambda::Url
   Properties: 
     AuthType: NONE
     TargetFunctionArn: !Ref MyLambdaFunction

  PermissionForURLInvoke:
     Type: AWS::Lambda::Permission
     Properties:
       FunctionName: !Ref MyLambdaFunction
       FunctionUrlAuthType: 'NONE'
       Action: lambda:InvokeFunctionUrl
       Principal: '*'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /

Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value: !GetAtt LambdaRole.Arn
    Export:
      Name: LambdaRole
  
  LambdaFunctionName:
    Value: !Ref MyLambdaFunction

  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value: !GetAtt MyLambdaFunction.Arn

  LambdaFunctionUrlOutput:
   Description: "The public HTTP URL for the Lambda function"
   Value: !GetAtt LambdaFunctionUrl.FunctionUrl